//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultTech1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public int id { get; set; }
        public string ques { get; set; }
        public int theory_id { get; set; }
        public int answers_id { get; set; }
    
        public virtual Answers Answers { get; set; }
        public virtual Theory Theory { get; set; }
    }
}
